### ISSUE TITLE
Failure with: TypeError: descriptor 'capitalize' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by MonsieurCellophane** [guokr/swagger-py-codegen#100]
Environment:
```
    Python 2.7.13 (default, May 10 2017, 20:04:28) 
    [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
```

Example failure:
```
    # swagger_py_codegen -s petStore.json example-app
    ................................Traceback (most recent call last):
  File "/opt/virtualenvs/engineering/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
...
 File "/opt/virtualenvs/engineering/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 11, in schema_var_name
    return ''.join(map(str.capitalize, path))
TypeError: descriptor 'capitalize' requires a 'str' object but received a 'unicode'
```

The (ugly) fix I found is rewriting this function in parser.py:
```
def schema_var_name(path):
    #ALF
    class_ = path[0].__class__
    return class_.join(class_(''),map(class_.capitalize, path))
    #return ''.join(map(str.capitalize, path))
```

**Comment by fantastao** [comment]
Can you show your petStore.json causing the failure?

**Comment by ciacicode** [comment]
Hi @fantastao  I tried to fix this in this pull request. Take a look, it's a tiny change but it should work. #101

**Comment by fantastao** [comment]
@ciacicode Your fix works well if there exist unicode strings supporting 'ascii' encoding, for example `u'a', u'!'`.That's fine! But what if variable `path` includes unicode strings like `u'ω', u'你好'`, `UnicodeEncodeError: 'ascii' codec can't encode character ...` will be raised if you try to `str` them. So how to avoid such failure depends on your definition in swagger spec, try not to use non-ascii characters in swagger `definitions`.

**Comment by ciacicode** [comment]
True that @fantastao - it's still not perfect.
