### ISSUE TITLE
Schema Definitions Are Not Deterministically Ordered

### ISSUE THREAD

**Issue by dagrooms52** [guokr/swagger-py-codegen#116]
**Background**
I am generating a Flask server from a Swagger document with multiple schema definitions. I am generating the server code at build time, and committing it in source control. 

**Actual Outcome**
Between two builds with no changes in my swagger.yaml, the file `schemas.py` moves a `Definitions...` entry between two different lines in the file; it is either the first `Definitions` entry, or the third. This is seen in the diff:
```
$ git diff
-DefinitionsWeirdType = {'type': 'object', 'blah': 'blah'}  # Hops from here..
DefinitionsOkType = {'type': 'object', 'blah': 'blah'}
DefinitionsFineType = {'type': 'object', 'blah': 'blah'}
+DefinitionsWeirdType = {'type': 'object', 'blah': 'blah'}  # To here
```

**Expected Outcome**
The file should not change between two builds. The `Definitions` variables should be sorted in a deterministic manner.

**Versions**
```
Python 3.6.5
swagger-py-codegen==0.3.2
swagger: "2.0"
```

**Additional Details**
I can work around this for now by only running my `swagger-py-codegen` task if changes are detected in my `swagger.yaml`.

**Comment by foodszhang** [comment]
@dagrooms52  Could you provide your swagger.yaml or a yaml that can stably reproduce this problem?
