### ISSUE TITLE
Only generates demo>v1>schemas.py

### ISSUE THREAD

**Issue by michielmulders** [guokr/swagger-py-codegen#123]
When I run swagger_py_codegen -s api.yml example-app -p demo
It only generates the schema file but no other files (doesn't work for any of the templates).
I used the default template for pets.

Any help for this or how this comes? Error message I get:
`TypeError: expected 1 arguments, got 0
`

**Comment by DDogeChan** [comment]
the same problem,pyrhon version is 3.6
