### ISSUE TITLE
none value validated

### ISSUE THREAD

**Issue by zongxiao** [guokr/swagger-py-codegen#16]
example:

    validator = Draft4Validator(schema)
    value = []
    schema = {'required': ['username'], 'properties': {'username': {'type': 'string', 'description': u'username'}}}
    
    errors = list(e.message for e in validator.iter_errors(value))

    errors 结果为 []

    单是结果应该是 ["'username' is a required property"] 才对

    这里 错误是因为 value 应该是一个 {}
https://github.com/guokr/swagger-py-codegen/blob/master/swagger_py_codegen/templates/flask/validators.tpl

**Comment by zongxiao** [comment]
https://github.com/guokr/swagger-py-codegen/pull/17

**Comment by Rejown** [comment]
'type': 'object'
