### ISSUE TITLE
parameters "in header" not working

### ISSUE THREAD

**Issue by adrpp** [guokr/swagger-py-codegen#35]
consider following "Path(s)" yaml definition:

/token/:
    get:
      summary: Obtain token
      parameters: 
       - name: username
         in: header
         required: true
         type: string
       - name: password
         in: header
         required: true
         type: string
         format: password
      responses:
         200:
           description: OK
           headers:
             x-auth-token:
              type: string

curl -X GET --header "Accept: application/json" --header "username: testuser" --header "password: xxx" "http://127.0.0.1:5000/v1/token/"

returns:

{
    "errors": [
        "'username' is a required property", 
        "'password' is a required property"
    ], 
    "message": "Unprocessable Entity"
}

**Comment by softlns** [comment]
The first letter of the parameter name which defined in header should be capitalized.

	paths:
	  /token:
	    get:
	      summary: Obtain token
	      parameters:
	        - name: Username
	          in: header
	          required: true
	          type: string
	        - name: Password
	          in: header
	          required: true
	          type: string
	      responses:
	        200:
	          description:  OK

**Comment by adrpp** [comment]
thanks, that's did the trick :)
btw, merry xmas and happy new year
