### ISSUE TITLE
I run the demo-ui , but in web browser, page not found.

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#37]
I run the command "python __init__.py". the server can start at port 5000, but in web browser, page not found ,there is the output in the page:
 "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."

and I found in the debug console, there is the following message:
[03/Jan/2016 21:38:54] "GET / HTTP/1.1" 404 -

what's wrong with my environment?

**Comment by Rejown** [comment]
What the contents of the swagger-doc? are you use the `api.yml` of this project source code?
you can find the valid paths in `api.yml`, for example: `http://127.0.0.1:5000/v1/oauth/auth_approach.json`.
`GET / HTTP/1.1` return 404 is correct, because the root path '/' is not defined in `api.yml`.

**Comment by LouisZou** [comment]
Thank you for your guidance.
I run the project according to the README.md. I used the file api.yml to generate the demo-ui and then want to run it to observe the result of swagger ui like the formal tool SwaggerUI.
that's meaning I need other codes or steps to realize the whole project, is it correct?

**Comment by Rejown** [comment]
The `api.yml` is valid and can be used for create a demo app, if you just want to try this tool, the `api.yml` is enough. with the `--spec` and `--ui` option it will include the `swagger-ui` codes, then you can visit `http://127.0.0.1:5000/static/swagger-ui/index.html` in a browser.

**Comment by LouisZou** [comment]
Thanks you very much.
the page of swagger ui is displayed normally. and I can use the UI to list other json file ,such as swagger.json in my web server.

another question, can we change the default port 5000 to 80? or do I need nginx for this issue?

**Comment by Rejown** [comment]
Your can supply the `port` argument for the `app.run()`, the flask document:
http://flask.pocoo.org/docs/0.10/api/#flask.Flask.run,
and the deployment options:
http://flask.pocoo.org/docs/0.10/deploying/

**Comment by LouisZou** [comment]
understood, I forget the app.run.
Thank you very much ,i will close this issue.
