### ISSUE TITLE
does this support the converting action between the yaml and json files?

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#39]
such as, I have a swagger definition file (api.yaml),
can we convert it to json using this tool?

**Comment by Rejown** [comment]
the swagger definition file can be both yaml and json format, it depends on the suffix of the file name, e.g. `api.json` means json format, and the `api.yml` means yaml format. so the converting is unnecessary.

**Comment by LouisZou** [comment]
Thanks a lot.
I need to study the base concept.
:)
