### ISSUE TITLE
using generated code as 'template' for real api code

### ISSUE THREAD

**Issue by adrpp** [guokr/swagger-py-codegen#40]
Hello,

sorry for bothering you with this question, but I didn't find anything related to this topic.
My question is how to override generated API methods (located under example_app/$basePath/api/*)

My point is to have a central point (api.yaml file) from which the code is generated and to extend the generated code with own logic / glue.

In other words, I would like to use the generated code not only for the docs / UI but as a 'template' which can be extended by own code.

As far I've seen, the generated methods code ("../api/_") is bound only at one "point" - that is routes.py.
Importing ../api/_ or $basePath/routes imports the stuff from **init** file.

Thanks a lot,
Rgds,
Adrian

**Comment by rushsinging** [comment]
The tool is to create files and generate basic code.It service for a **flask** app.

So after generating, you can import the **blueprint** into your app from the genreated files.

When creating files, it will ingore files if they exist on the path.So if you added your own code to some files, rerunning will not overwrite your code.

So, just add your own code into the files. :p
