### ISSUE TITLE
How to set cookie in the tryout action in the final swagger-ui 

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#41]
I wrote a restful web application that need token and authentication to access the api.
And I can get the token from login to the api  http://api/authenticate and can get the cookie.

how do I set the cookie in the next call ? such as:
when User click the button named "try out", it will run the command:
curl -b cookie_file ...

need I define the requirement of cookie in the original definition files (swagger.json)?

**Comment by Rejown** [comment]
In our design, the HTTP RESTful API will not accept _cookies_, it accept _token_ in the request header. In other words, the RESTful API is not browser-oriented. 
The main reason is the cookies are unsafe. you can google "restful api + cookies" for more information about this subject.
The appropriate authentication approach is OAuth and scope in the swagger specification:
http://swagger.io/specification/#securityDefinitionsObject
For the browser usage, you should implement your own cookies business.

**Comment by LouisZou** [comment]
Thanks. 
Now my Http RESTful API is designed to need cookie to get the authentication, that's meaning, I need to change it.
Is there any other method if using the current model?

**Comment by Rejown** [comment]
The _swagger-py-codegen_ generated code is not a complete app, but only a skeleton. you can change and extend the skeleton code on your own way, even custom the code template.
There is nothing magic, the generated code is just a flask app(precisely flask-restful app), so extend the app should follow the flask way(and flask-restful). 
some links maybe useful:
http://flask.pocoo.org/docs/0.10/quickstart/#sessions
https://flask-login.readthedocs.org/en/latest/
http://flask.pocoo.org/snippets/3/

**Comment by LouisZou** [comment]
Thanks Rejown.
I'am studying the swagger and Flask in Python.
