### ISSUE TITLE
Where is the realize of curl command for the swagger-ui.js

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#43]
I want to re-write the curl command and execute it to access the Restful API Host to get/post request and then analyze the response to get some information (Header and Body).
Sorry for that I don't know where is the realization code for it.

I found there is the following points in swagger-ui.js:
31919:    var curlCommand = this.model.asCurl(this.map);
I know it is the point for making the curl command but I know where is executing for this command , and where is the callback for analyzing the response and then overwrite the response form in the web page.

**Comment by Rejown** [comment]
Maybe you can ask this question in the [swagger-ui project](https://github.com/swagger-api/swagger-ui), sorry about this.

**Comment by LouisZou** [comment]
Thanks Rejown.
I'm a fresh man in swagger.

**Comment by LouisZou** [comment]
I debug the swagger-ui.js.
I found the code : 

  if (obj.body) {
    r.send(obj.body);
  }

**Comment by LouisZou** [comment]
is here the real execution of the http request?

**Comment by LouisZou** [comment]
where is the flow of the code r.send?
 is it yet in swagger-ui.js or other lib? such as jquery.js ?
