### ISSUE TITLE
hi Rejown, how to contact to you and discuss the knowlegdes about this project.

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#50]
hi Rejown,
if convenient, could you please tell your IM account?such as , QQ or wechat?
I have some questions about this porject.
I'm stduing the swagger now.

:+1:

**Comment by softlns** [comment]
U can communicate with me about this porject.
QQ: 745379262

**Comment by LouisZou** [comment]
Thanks, I will contact to you with QQ.

**Comment by LouisZou** [comment]
But the QQ is no response?
laugh:)
