### ISSUE TITLE
处理model中的动态的一对多加载

### ISSUE THREAD

**Issue by zrq495** [guokr/swagger-py-codegen#52]
https://github.com/guokr/swagger-py-codegen/blob/master/swagger_py_codegen/jsonschema.py#L174

这里的判断可否换成 
```
import collections
if isinstance(data, collections.Iterable):
```
或者
```
if hasattr(data, '__iter__'):
```
这样我在model中定义一对多的关系的时候可以直接使用 `lazy='dynamic'`

**Comment by softlns** [comment]
Thanks!
