### ISSUE TITLE
Add Falcon support

### ISSUE THREAD

**Issue by advance512** [guokr/swagger-py-codegen#82]
Right now, this project can only generate Flask code.
How about we add support for additional frameworks, specifically for Falcon?

It would only require creating a FalconGenerator class (in falcon.py module) and appropriate templates, most of which would be fairly similar.

Is this something you'd consider merging in?

**Comment by Rejown** [comment]
Great idea, in fact, we are also considering this matter, but there is no formal schedule, and we do not know much about Falcon. Very welcome PR.

**Comment by jizhouli** [comment]
@advance512 Thanks for your suggestions, now Falcon is supported, please try it.
