### ISSUE TITLE
Generated operations at UI is not sorted

### ISSUE THREAD

**Issue by leslie-wang** [guokr/swagger-py-codegen#95]
Need sorted based on alphabet order, or the other in the spec. Currently it is out of order, so hard to navigate when number of operations grow.

**Comment by leslie-wang** [comment]
Just update what I found. Seems like the problem happens during convert yaml file to json stage. Converted json file is out of order. If I replace json file with right one, it can display correctly.

**Comment by fantastao** [comment]
As I know, operations would be grouped by tags if you define them in swagger spec.
