### ISSUE TITLE
Security is not processed nor enforced

### ISSUE THREAD

**Issue by omerbn** [guokr/swagger-py-codegen#98]
Take for example this (part of) swagger file:

> swagger: '2.0'
>
>info:
&nbsp;&nbsp;version: '1.0'
&nbsp;&nbsp;title: API
&nbsp;&nbsp;description: API.
>
>securityDefinitions:
&nbsp;&nbsp;Auth-email:
&nbsp;&nbsp;&nbsp;&nbsp;description: |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User-Email
&nbsp;&nbsp;&nbsp;&nbsp;type: apiKey
&nbsp;&nbsp;&nbsp;&nbsp;in: header
&nbsp;&nbsp;&nbsp;&nbsp;name: Auth-email
&nbsp;&nbsp;Auth-IP:
&nbsp;&nbsp;&nbsp;&nbsp;description: |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If login request is not sent from the same IP session is created for, you should send it.
&nbsp;&nbsp;&nbsp;&nbsp;type: apiKey
&nbsp;&nbsp;&nbsp;&nbsp;in: header
&nbsp;&nbsp;&nbsp;&nbsp;name: Auth-IP 
&nbsp;&nbsp;JWT:
&nbsp;&nbsp;&nbsp;&nbsp;description: |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For accessing the API a valid JWT
&nbsp;&nbsp;&nbsp;&nbsp;type: apiKey
&nbsp;&nbsp;&nbsp;&nbsp;name: Authorization
&nbsp;&nbsp;&nbsp;&nbsp;in: header
>
> \# default JWT security
security: [ { JWT: [] }]
>
>paths:
&nbsp;&nbsp;/login:
&nbsp;&nbsp;&nbsp;&nbsp;get:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;summary: login
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;security:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Auth-email
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Auth-IP 
>
>&nbsp;&nbsp;/query
&nbsp;&nbsp;&nbsp;&nbsp;get:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;summary: query

Both requests have security configurations and neither is enforced/checked.
I think it should be.

Any objections that I'll do it?

**Comment by fantastao** [comment]
[OAuth2-Scopes-Usage](https://github.com/guokr/swagger-py-codegen/wiki/OAuth2-Scopes-Usage) maybe some help for you.
